questions:
- id: f092d62f
  question: You have a deployment named 'webapp' with label 'app=webapp'. Create a
    ClusterIP service named 'webapp-svc' to expose the deployment on port 80.
  success_criteria:
  - YAML syntax is valid
  - Required Kubernetes resources are defined
  - Resource specifications are complete
  suggestions:
  - kubectl expose deployment webapp --name=webapp-svc --port=80 --target-port=80
  source: https://stackoverflow.com/questions/62964958/expose-a-web-app-on-port-80-using-kubernetes-and-minikube
  requirements:
    kind: Service
    metadata:
      name: webapp-svc
    spec:
      ports:
      - port: 80
        targetPort: 80
      selector:
        app: webapp
- id: daca4b87
  question: Create a manifest for a NodePort service named 'webapp-nodeport'. The
    service should forward traffic from a port on the node to port 80 on pods with
    the label 'app=webapp'.
  success_criteria:
  - YAML syntax is valid
  - Required Kubernetes resources are defined
  - Resource specifications are complete
  suggestions:
  - apiVersion: v1
    kind: Service
    metadata:
      name: webapp-nodeport
    spec:
      ports: &id002
      - port: 80
        protocol: TCP
        targetPort: 80
      selector: &id001
        app: webapp
      type: NodePort
  source: https://kubernetes.io/docs/concepts/services-networking/service/
  requirements:
    kind: Service
    metadata:
      name: webapp-nodeport
    spec:
      selector: *id001
      ports: *id002
- id: feb58902
  question: Service manifest (ClusterIP) exposing app=web on port 80 to targetPort
    8080.
  success_criteria:
  - YAML syntax is valid
  - Required Kubernetes resources are defined
  - Resource specifications are complete
  suggestions:
  - apiVersion: v1
    kind: Service
    metadata:
      name: web
    spec:
      ports: &id004
      - port: 80
        targetPort: 8080
      selector: &id003
        app: web
  source: https://kubernetes.io/docs/concepts/services-networking/service/
  requirements:
    kind: Service
    metadata:
      name: web
    spec:
      selector: *id003
      ports: *id004
- id: 6c9bbdba
  question: Headless Service manifest for app=db on port 5432.
  success_criteria:
  - YAML syntax is valid
  - Required Kubernetes resources are defined
  - Resource specifications are complete
  suggestions:
  - apiVersion: v1
    kind: Service
    metadata:
      name: db
    spec:
      clusterIP: None
      ports: &id006
      - port: 5432
        targetPort: 5432
      selector: &id005
        app: db
  source: https://stackoverflow.com/questions/69611827/kubernetes-is-there-any-way-to-get-headless-service-endpoint-info-in-container
  requirements:
    kind: Service
    metadata:
      name: db
    spec:
      selector: *id005
      ports: *id006
- id: 319fc60e
  question: Expose deployment frontend on port 80 as a ClusterIP service named frontend-svc.
  success_criteria:
  - YAML syntax is valid
  - Required Kubernetes resources are defined
  - Resource specifications are complete
  suggestions:
  - kubectl expose deployment frontend --port=80 --type=ClusterIP --name=frontend-svc
  source: https://kubernetes.io/vi/docs/reference/kubectl/cheatsheet/#:~:text=,port%3D8000
  requirements:
    kind: Service
    metadata:
      name: frontend-svc
    spec:
      ports:
      - port: 80
      type: ClusterIP
      selector:
        app: frontend
- id: 240252c4
  question: List all services.
  success_criteria:
  - YAML syntax is valid
  - Required Kubernetes resources are defined
  - Resource specifications are complete
  suggestions:
  - kubectl get services
  source: https://kubernetes.io/docs/reference/kubectl/quick-reference/#:~:text=,current%20namespace%2C%20with%20more%20details
- id: 6e65d4ef
  question: Describe service frontend-svc.
  success_criteria:
  - YAML syntax is valid
  - Required Kubernetes resources are defined
  - Resource specifications are complete
  suggestions:
  - kubectl describe service frontend-svc
  source: https://kubernetes.io/vi/docs/reference/kubectl/cheatsheet/#:~:text=,pod)
- id: 9bfae12b
  question: Delete service frontend-svc.
  success_criteria:
  - YAML syntax is valid
  - Required Kubernetes resources are defined
  - Resource specifications are complete
  suggestions:
  - kubectl delete service frontend-svc
  source: https://kubernetes.io/vi/docs/reference/kubectl/cheatsheet/#:~:text=,port%3D8000
- id: 25d4db36
  question: 'Create a Service `my-service` that selects pods with label `app: MyApp`.
    The service should expose TCP port 80 and target port 8080 on the pods.'
  success_criteria:
  - YAML syntax is valid
  - Required Kubernetes resources are defined
  - Resource specifications are complete
  suggestions:
  - apiVersion: v1
    kind: Service
    metadata:
      name: my-service
    spec:
      ports: &id008
      - port: 80
        protocol: TCP
        targetPort: 8080
      selector: &id007
        app: MyApp
  source: https://kubernetes.io/docs/tutorials/services/connect-applications-service/
  requirements:
    kind: Service
    metadata:
      name: my-service
    spec:
      selector: *id007
      ports: *id008
