- id: manifests::services::change-port
  prompt: "Edit the Service manifest to change the `targetPort` from 80 to 8080."
  type: yaml_edit
  category: "YAML Editing Practice"
  initial_files:
    service.yaml: |
      apiVersion: v1
      kind: Service
      metadata:
        name: my-service
      spec:
        selector:
          app: MyApp
        ports:
          - protocol: TCP
            port: 80
            targetPort: 80
  correct_yaml: |
    apiVersion: v1
    kind: Service
    metadata:
      name: my-service
    spec:
      selector:
        app: MyApp
      ports:
        - protocol: TCP
          port: 80
          targetPort: 8080
