- id: manifests::deployments::increase-replicas
  prompt: "Edit the deployment manifest to increase the number of replicas to 3."
  type: yaml_edit
  category: "YAML Editing Practice"
  initial_files:
    deployment.yaml: |
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: nginx-deployment
      spec:
        replicas: 1
        selector:
          matchLabels:
            app: nginx
        template:
          metadata:
            labels:
              app: nginx
          spec:
            containers:
            - name: nginx
              image: nginx:1.14.2
  correct_yaml: |
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: nginx-deployment
    spec:
      replicas: 3
      selector:
        matchLabels:
          app: nginx
        template:
          metadata:
            labels:
              app: nginx
        spec:
          containers:
          - name: nginx
            image: nginx:1.14.2
- id: manifests::deployments::change-image
  prompt: "Edit the deployment manifest to change the container image from `nginx:1.14.2` to `nginx:1.16.1`."
  type: yaml_edit
  category: "YAML Editing Practice"
  initial_files:
    deployment.yaml: |
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: nginx-deployment
      spec:
        replicas: 2
        selector:
          matchLabels:
            app: nginx
        template:
          metadata:
            labels:
              app: nginx
          spec:
            containers:
            - name: nginx
              image: nginx:1.14.2
  correct_yaml: |
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: nginx-deployment
    spec:
      replicas: 2
      selector:
        matchLabels:
          app: nginx
        template:
          metadata:
            labels:
              app: nginx
        spec:
          containers:
          - name: nginx
            image: nginx:1.16.1
- id: manifests::deployments::add-init-container
  prompt: "A Deployment needs an init container to prepare a volume. For the `test-init-container` Deployment in namespace `mars`, add an `initContainer` named `init-con`. It should use the `busybox:1.31.0` image and run a command to create a file: `echo 'check this out!' > /tmp/web-content/index.html`. The init container should mount the existing `web-content` volume at `/tmp/web-content`."
  type: yaml_edit
  category: "YAML Editing Practice"
  initial_files:
    deployment.yaml: |
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: test-init-container
        namespace: mars
      spec:
        replicas: 1
        selector:
          matchLabels:
            id: test-init-container
        template:
          metadata:
            labels:
              id: test-init-container
          spec:
            volumes:
            - name: web-content
              emptyDir: {}
            containers:
            - name: nginx
              image: nginx:1.17.3-alpine
              volumeMounts:
              - name: web-content
                mountPath: /usr/share/nginx/html
              ports:
              - containerPort: 80
  correct_yaml: |
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: test-init-container
      namespace: mars
    spec:
      replicas: 1
      selector:
        matchLabels:
          id: test-init-container
      template:
        metadata:
          labels:
            id: test-init-container
        spec:
          volumes:
          - name: web-content
            emptyDir: {}
          initContainers:
          - name: init-con
            image: busybox:1.31.0
            command: ['sh', '-c', 'echo "check this out!" > /tmp/web-content/index.html']
            volumeMounts:
            - name: web-content
              mountPath: /tmp/web-content
          containers:
          - name: nginx
            image: nginx:1.17.3-alpine
            volumeMounts:
            - name: web-content
              mountPath: /usr/share/nginx/html
            ports:
            - containerPort: 80
