name: Publish to PyPI

on:
  workflow_dispatch:
    inputs:
      bump_type:
        description: 'Type of version bump (major, minor, patch)'
        required: true
        default: 'patch'
        type: choice
        options:
          - major
          - minor
          - patch

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: release
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install publishing dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build twine

    - name: Determine Version Bump Type (from input)
      id: get_bump_type
      run: |
        echo "VERSION_BUMP_TYPE=${{ github.event.inputs.bump_type }}" >> "$GITHUB_OUTPUT"

    - name: Bump Version
      env:
        BUMP_TYPE: ${{ steps.get_bump_type.outputs.VERSION_BUMP_TYPE }}
      run: |
        pip install semver
        python scripts/bump_version.py

    - name: Build package
      run: python -m build

    - name: Publish to PyPI
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
      run: twine upload dist/*